name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: lutris-wine
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly
          target: x86_64-unknown-linux-gnu

      - name: Build tray
        run: >
          sudo apt update -y && sudo apt install dbus libdbus-1-dev -y;
          cd lw-tray ;
          rustup component add rust-src --toolchain nightly ;
          cargo build --release ;
          cd ../ ;

      - name: Build archlinux packages
        uses: countstarlight/arch-makepkg-action@master
        with:
          scripts: "cd lwrap && makepkg --nodeps && cd ../ && makepkg --nodeps"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lutris-wine-git-*.pkg*
            lwrap/lwrap-*.pkg*
            target/x86_64-unknown-linux-gnu/release/lw-tray
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
