name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: lutris-wine
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build archlinux packages
        uses: countstarlight/arch-makepkg-action@master
        with:
          scripts: "cd lwrap && makepkg --nodeps && cd ../ && makepkg --nodeps"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lutris-wine-git-*.pkg*
            lwrap/lwrap-*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
